version: '3.7'
 
services:
  training:
    image: training
    volumes: 
      - ./imgs:/src/imgs
      - ./model:/src/model

  backend:
    image: backend
    depends_on: 
      - training
    ports:
      - 5000:5000
    volumes:
      - ./model:/src/model

  front:
    image: frontend
    depends_on: 
      - backend
    ports: 
      - 3000:3000