version: "3.6"
services:
  frontend:
    build: ../../part-1/1.5/frontend-example-docker-master
    ports:
     - 5000:5000
    environment:
     - API_URL=http://localhost:8000
  backend:
    build: ../../part-1/1.6/backend-example-docker-master
    ports:
     - 8000:8000
    volumes:
     - ../../part-1/1.6//backend-example-docker-master/logs.txt:/usr/src/app/logs.txt
    environment:
     - FRONT_URL=http://localhost:5000
     - REDIS=redis
     - DB_USERNAME=postgres
     - DB_PASSWORD=messagermessagesdb
     - DB_HOST=messager
    depends_on:
     - redis
     - postgres-db
  redis:
    image: redis:alpine
  postgres-db:
    image: postgres
    restart: always
    environment:
     - POSTGRES_PASSWORD=messagermessagesdb
