version: "3.5"
services:
  frontend:
    build: ../../part-1/1.5/frontend-example-docker-master
    ports:
    - 5000:5000
    environment:
    - API_URL=http://localhost:8000
  backend:
    build: ../../part-1/1.6/backend-example-docker-master
    ports:
    - 8000:8000
    volumes:
    - ../../part-1/1.6//backend-example-docker-master/logs.txt:/usr/src/app/logs.txt
    environment:
    - FRONT_URL=http://localhost:5000
    - REDIS=redis
    depends_on:
    - redis
  redis:
    image: redis:alpine